/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KabinetRouteImport } from './routes/kabinet'
import { Route as KirishRouteImport } from './routes/kirish'
import { Route as RoyxatdanOtishRouteImport } from './routes/royxatdan-otish'
import { Route as UstaPanelRouteImport } from './routes/usta-panel'
import { Route as XabarlarRouteImport } from './routes/xabarlar'
import { Route as BuyurtmaUstaIdRouteImport } from './routes/buyurtma.$ustaId'
import { Route as KategoriyalarIndexRouteImport } from './routes/kategoriyalar.index'
import { Route as KategoriyalarSlugRouteImport } from './routes/kategoriyalar.$slug'
import { Route as UstalarIndexRouteImport } from './routes/ustalar.index'
import { Route as UstalarUstaIdRouteImport } from './routes/ustalar.$ustaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KabinetRoute = KabinetRouteImport.update({
  id: '/kabinet',
  path: '/kabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const KirishRoute = KirishRouteImport.update({
  id: '/kirish',
  path: '/kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyxatdanOtishRoute = RoyxatdanOtishRouteImport.update({
  id: '/royxatdan-otish',
  path: '/royxatdan-otish',
  getParentRoute: () => rootRouteImport,
} as any)
const UstaPanelRoute = UstaPanelRouteImport.update({
  id: '/usta-panel',
  path: '/usta-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const XabarlarRoute = XabarlarRouteImport.update({
  id: '/xabarlar',
  path: '/xabarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyurtmaUstaIdRoute = BuyurtmaUstaIdRouteImport.update({
  id: '/buyurtma/$ustaId',
  path: '/buyurtma/$ustaId',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriyalarIndexRoute = KategoriyalarIndexRouteImport.update({
  id: '/kategoriyalar/',
  path: '/kategoriyalar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriyalarSlugRoute = KategoriyalarSlugRouteImport.update({
  id: '/kategoriyalar/$slug',
  path: '/kategoriyalar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UstalarIndexRoute = UstalarIndexRouteImport.update({
  id: '/ustalar/',
  path: '/ustalar/',
  getParentRoute: () => rootRouteImport,
} as any)
const UstalarUstaIdRoute = UstalarUstaIdRouteImport.update({
  id: '/ustalar/$ustaId',
  path: '/ustalar/$ustaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kabinet': typeof KabinetRoute
  '/kirish': typeof KirishRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/usta-panel': typeof UstaPanelRoute
  '/xabarlar': typeof XabarlarRoute
  '/buyurtma/$ustaId': typeof BuyurtmaUstaIdRoute
  '/kategoriyalar/$slug': typeof KategoriyalarSlugRoute
  '/ustalar/$ustaId': typeof UstalarUstaIdRoute
  '/kategoriyalar/': typeof KategoriyalarIndexRoute
  '/ustalar/': typeof UstalarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kabinet': typeof KabinetRoute
  '/kirish': typeof KirishRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/usta-panel': typeof UstaPanelRoute
  '/xabarlar': typeof XabarlarRoute
  '/buyurtma/$ustaId': typeof BuyurtmaUstaIdRoute
  '/kategoriyalar/$slug': typeof KategoriyalarSlugRoute
  '/ustalar/$ustaId': typeof UstalarUstaIdRoute
  '/kategoriyalar': typeof KategoriyalarIndexRoute
  '/ustalar': typeof UstalarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kabinet': typeof KabinetRoute
  '/kirish': typeof KirishRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/usta-panel': typeof UstaPanelRoute
  '/xabarlar': typeof XabarlarRoute
  '/buyurtma/$ustaId': typeof BuyurtmaUstaIdRoute
  '/kategoriyalar/$slug': typeof KategoriyalarSlugRoute
  '/ustalar/$ustaId': typeof UstalarUstaIdRoute
  '/kategoriyalar/': typeof KategoriyalarIndexRoute
  '/ustalar/': typeof UstalarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kabinet'
    | '/kirish'
    | '/royxatdan-otish'
    | '/usta-panel'
    | '/xabarlar'
    | '/buyurtma/$ustaId'
    | '/kategoriyalar/$slug'
    | '/ustalar/$ustaId'
    | '/kategoriyalar/'
    | '/ustalar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kabinet'
    | '/kirish'
    | '/royxatdan-otish'
    | '/usta-panel'
    | '/xabarlar'
    | '/buyurtma/$ustaId'
    | '/kategoriyalar/$slug'
    | '/ustalar/$ustaId'
    | '/kategoriyalar'
    | '/ustalar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kabinet'
    | '/kirish'
    | '/royxatdan-otish'
    | '/usta-panel'
    | '/xabarlar'
    | '/buyurtma/$ustaId'
    | '/kategoriyalar/$slug'
    | '/ustalar/$ustaId'
    | '/kategoriyalar/'
    | '/ustalar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KabinetRoute: typeof KabinetRoute
  KirishRoute: typeof KirishRoute
  RoyxatdanOtishRoute: typeof RoyxatdanOtishRoute
  UstaPanelRoute: typeof UstaPanelRoute
  XabarlarRoute: typeof XabarlarRoute
  BuyurtmaUstaIdRoute: typeof BuyurtmaUstaIdRoute
  KategoriyalarSlugRoute: typeof KategoriyalarSlugRoute
  UstalarUstaIdRoute: typeof UstalarUstaIdRoute
  KategoriyalarIndexRoute: typeof KategoriyalarIndexRoute
  UstalarIndexRoute: typeof UstalarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabinet': {
      id: '/kabinet'
      path: '/kabinet'
      fullPath: '/kabinet'
      preLoaderRoute: typeof KabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirish': {
      id: '/kirish'
      path: '/kirish'
      fullPath: '/kirish'
      preLoaderRoute: typeof KirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royxatdan-otish': {
      id: '/royxatdan-otish'
      path: '/royxatdan-otish'
      fullPath: '/royxatdan-otish'
      preLoaderRoute: typeof RoyxatdanOtishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usta-panel': {
      id: '/usta-panel'
      path: '/usta-panel'
      fullPath: '/usta-panel'
      preLoaderRoute: typeof UstaPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xabarlar': {
      id: '/xabarlar'
      path: '/xabarlar'
      fullPath: '/xabarlar'
      preLoaderRoute: typeof XabarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyurtma/$ustaId': {
      id: '/buyurtma/$ustaId'
      path: '/buyurtma/$ustaId'
      fullPath: '/buyurtma/$ustaId'
      preLoaderRoute: typeof BuyurtmaUstaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoriyalar/': {
      id: '/kategoriyalar/'
      path: '/kategoriyalar'
      fullPath: '/kategoriyalar/'
      preLoaderRoute: typeof KategoriyalarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoriyalar/$slug': {
      id: '/kategoriyalar/$slug'
      path: '/kategoriyalar/$slug'
      fullPath: '/kategoriyalar/$slug'
      preLoaderRoute: typeof KategoriyalarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustalar/': {
      id: '/ustalar/'
      path: '/ustalar'
      fullPath: '/ustalar/'
      preLoaderRoute: typeof UstalarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustalar/$ustaId': {
      id: '/ustalar/$ustaId'
      path: '/ustalar/$ustaId'
      fullPath: '/ustalar/$ustaId'
      preLoaderRoute: typeof UstalarUstaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KabinetRoute: KabinetRoute,
  KirishRoute: KirishRoute,
  RoyxatdanOtishRoute: RoyxatdanOtishRoute,
  UstaPanelRoute: UstaPanelRoute,
  XabarlarRoute: XabarlarRoute,
  BuyurtmaUstaIdRoute: BuyurtmaUstaIdRoute,
  KategoriyalarSlugRoute: KategoriyalarSlugRoute,
  UstalarUstaIdRoute: UstalarUstaIdRoute,
  KategoriyalarIndexRoute: KategoriyalarIndexRoute,
  UstalarIndexRoute: UstalarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
